Test yaim configuration: - JPPS: libtar in /opt too, propagate the error from startup script - JPIS: fixed strange config file loading crash

diff --git a/org.glite.jp.primary/config/startup b/org.glite.jp.primary/config/startup
--- a/org.glite.jp.primary/config/startup
+++ b/org.glite.jp.primary/config/startup
@@ -67,21 +67,25 @@ start()
 	fi
 
 	echo -n Starting glite-jp-primarystoraged ...
-	su - $GLITE_USER -c "LD_LIBRARY_PATH=$GLOBUS_LOCATION/lib:$GLITE_LOCATION/lib:$CARES_LOCATION/lib \
+	su - $GLITE_USER -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GLOBUS_LOCATION/lib:$GLITE_LOCATION/lib \
 		$GLITE_LOCATION/bin/glite-jp-primarystoraged \
 		$GLITE_JP_DEBUG \
 		-P $GLITE_LOCATION/lib/glite_lb_plugin.so -P $GLITE_LOCATION/lib/glite-jp-sandbox.so \
 		$creds -a '$GLITE_JP_PRIMARY_PEERS' \
 		-i '$pidfile' -p $GLITE_JP_PRIMARY_PORT $GLITE_JP_PRIMARY_SPECIAL \
 		-BI,'$GLITE_JP_PRIMARY_INTERNAL' -BE,'$GLITE_JP_PRIMARY_EXTERNAL' \
-		${GLITE_JP_PRIMARY_DBCS_OPTION} " && echo " done" || echo " FAILED"
+		${GLITE_JP_PRIMARY_DBCS_OPTION} " && echo " done"
+	if [ $? != 0 ]; then
+		echo " FAILED"
+		return 1
+	fi
 
 	echo -n Starting JP gridftp server ...
 	su - $GLITE_USER -c "X509_USER_CERT=\"$X509_USER_CERT\" \
                 X509_USER_KEY=\"$X509_USER_KEY\" \
                 GLITE_USER=\"$GLITE_USER\" \
                 FTPBE_INT_PREFIX=\"$GLITE_JP_PRIMARY_INTERNAL\" \
-                LD_LIBRARY_PATH=$GLOBUS_LOCATION/lib:$GLITE_LOCATION/lib \
+                LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GLOBUS_LOCATION/lib:$GLITE_LOCATION/lib \
 		FTPBE_DB_CS=$GLITE_JP_PRIMARY_DBCS \
 		GSI_AUTHZ_CONF=$GLITE_JP_GSI_AUTHZ \
 		$GLOBUS_LOCATION/sbin/globus-gridftp-server -debug -s -p $GLITE_JP_PRIMARY_FTP_PORT & \
